### PR TITLE
➕ Add Storybook

### PR DESCRIPTION
**Pull request by m-wiemers**
- Add storybook
- Set storybook example Button in components-directory
- Set new path in `.storybook/main.js`
- Clean `pages/index.tsx` and add Buttons from storybook
- Ignore `storybook-static` in all ignore-files
- Add `.eslintignore`

https://storybook.js.org/docs/react/get-started/install

### CODE REVIEW

**Comment by DNaunin** [comment]
LGTM! 🚀

**Comment by RonjaMeinecke** [comment]
you wrote • Add .eslinticnore and probably meant eslintignore 😊

**Comment by RonjaMeinecke** [comment]
all the i**g**nores are with a c intead of a g 😉

**Review by RonjaMeinecke — APPROVED** [review]
GJ 💪

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Comment by SilviaBarcellini** [comment]
Good job! 👍

**Review by sweisz — APPROVED** [review]
lgtm 👍

**Review by mrana17 — APPROVED** [review]
You are an artist! 👨‍🎨

**Review by JuKahl — APPROVED** [review]
smart code from an even smarter guy 🚀

**Pull request merged**
