### PR TITLE
➕ Add eslint

### PR DESCRIPTION
**Pull request by m-wiemers**
- Add ESLint
- solve conflicts with react
- Add Script `eslint` to check files

https://eslint.org/docs/user-guide/getting-started
https://nextjs.org/docs/basic-features/typescript

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Comment by HorstFrank** [comment]
LGTM .... ready to deploy!

**Review by lmachens — APPROVED** [review]
🚀

**Review by SilviaBarcellini — APPROVED** [review]
Great job! 👍

**Pull request merged**
