### PR TITLE
➕ Add husky and lintstaged

### PR DESCRIPTION
**Pull request by m-wiemers**
- Add husky `npm install husky --save-dev && npx husky init`
- Add lint-staged `npm i -D lint-staged`
- Add `.lintstagedrc.json`
- Change call in `./husky/pre-commit` to `npx lint-staged --config .lintstagedrc.json`
- Change script `prettify` from `--write` to `--check`
- Add `prepare` and `test` scripts in package.json
- Add pre-push with `npx husky add .husky/pre-push "npm test"`

use `--no-verify` to skip pre-check in git commands

https://typicode.github.io/husky/#/
https://github.com/okonet/lint-staged

### CODE REVIEW

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by mewiemers — APPROVED** [review]
GJ😎

**Review by christophvogel — APPROVED** [review]
LGTM 👍

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by DNaunin** [comment]
GJ! 🚀

**Pull request merged**
