### PR TITLE
✨ Add custom Server

### PR DESCRIPTION
**Pull request by m-wiemers**
A custom server supports consistent connections with web sockets or databases and allows custom routing.
Guides:
https://nextjs.org/docs/advanced-features/custom-server
https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript

Steps:

- Add server folder with `server/index.ts`
- `npm i -D nodemon ts-node` which is required for the new dev script.
- Add `tsconfig.server.json` for a custom TypeScript config for the server side. The existing `tsconfig` is extended.
- Add `nodemon.json` to configure nodemon.
- Add and update `dev`, `build-next`, `build-server`, build and start scripts in the package.json

- npm run dev is used in development with hot module replacement.
- npm run build creates optimized client, storybook and server builds.
- npm start calls the server build.

https://nextjs.org/docs/advanced-features/custom-server
https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript

### CODE REVIEW

**Review by fgottesmann — APPROVED** [review]
lgtm! :)

**Review by DNaunin — APPROVED** [review]
LGTM! 🚀

**Review by RonjaMeinecke — APPROVED** [review]
GJ 🚀

**Review by christophvogel — APPROVED** [review]
GJ 💯

**Review by fre-ben — APPROVED** [review]
Marcelmazing! 🤖

**Review by mrana17 — APPROVED** [review]
Coding is meant for you! 💪

**Review by mewiemers — APPROVED** [review]
this code rocks, see us in a coding date 💯❤

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by SilviaBarcellini** [comment]
All great! 👍

**Pull request merged**
